language: python

python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "pypy3"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - python setup.py install 

script:
  - nosetests --with-coverage --cover-package=ordered_set

after_success:
  - pip install --quiet coveralls
  - coveralls
